### PR TITLE
Log and continue if install uuid can't be retrieved

### PR DESCRIPTION
**Pull request by LLParse**

### CODE REVIEW

**Comment by joshwget** [comment]
Does the git mirror work if the UUID if empty?

**Comment by LLParse** [comment]
@joshwget Yes. For instance, you may access the new endpoint in a browser (which will not send the header, obviously).

https://git.rancher.io/repos/rancher-catalog/commits/master

**Comment by joshwget** [comment]
It might be useful to set the UUID to all zeros by default for consistency (and to see how many setups actually hit this error as well).

Just an idea though, LGTM in any case.

**Comment by cjellick** [comment]
LGTM

**Pull request merged**
